name: Package branches

on:
  push:
    tags:
      - 'v*.*.*'  # e.g. v5.0.2

jobs:
  package-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install rimraf globally
        run: npm install -g rimraf

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create version branch and build
        run: |
          git checkout -B $VERSION
          cd packages/tsruntime
          npm install --include=dev
          npm run build
          cd ../../
          # Prepare temporary folder with necessary files
          mkdir -p tmp_branch
          cp -r packages/tsruntime/dist tmp_branch/
          cp packages/tsruntime/package.json tmp_branch/
          [ -f packages/tsruntime/package-lock.json ] && cp packages/tsruntime/package-lock.json tmp_branch/ || true
          [ -f packages/tsruntime/yarn.lock ] && cp packages/tsruntime/yarn.lock tmp_branch/ || true
          [ -f README.md ] && cp README.md tmp_branch/ || true
          [ -f LICENSE ] && cp LICENSE tmp_branch/ || true
          # Clean root except .git and tmp_branch
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'tmp_branch' -exec rm -rf {} +
          # Move prepared files to root
          mv tmp_branch/* tmp_branch/.* . 2>/dev/null || true
          rmdir tmp_branch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: prepare package for $VERSION"
          git push origin refs/heads/$VERSION:refs/heads/$VERSION --force

      - name: Update eveble branch
        run: |
          # Go back to the original tag to get source code
          git checkout tags/$VERSION
          git checkout -B eveble
          cd packages/tsruntime
          npm install --include=dev
          npm run build
          cd ../../
          mkdir -p tmp_branch
          cp -r packages/tsruntime/dist tmp_branch/
          cp packages/tsruntime/package.json tmp_branch/
          [ -f packages/tsruntime/package-lock.json ] && cp packages/tsruntime/package-lock.json tmp_branch/ || true
          [ -f packages/tsruntime/yarn.lock ] && cp packages/tsruntime/yarn.lock tmp_branch/ || true
          [ -f README.md ] && cp README.md tmp_branch/ || true
          [ -f LICENSE ] && cp LICENSE tmp_branch/ || true
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'tmp_branch' -exec rm -rf {} +
          mv tmp_branch/* tmp_branch/.* . 2>/dev/null || true
          rmdir tmp_branch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update eveble branch to $VERSION"
          git push origin refs/heads/eveble:refs/heads/eveble --force